version: '3'

services:
    shardbase:
        build:
            dockerfile: ./docker/shard/Dockerfile
            context: .
    spqrbase:
        build:
            dockerfile: ./docker/spqr/Dockerfile
            context: .
    shard1:
        image:
            spqr_shardbase
        ports:
            - "7432:6432"
        hostname: spqr_shard_1_1
    shard2:
        image:
            spqr_shardbase
        ports:
            - "7433:6432"
        hostname: spqr_shard_2_1
    coordinator:
        build:
            dockerfile: ./docker/coordinator/Dockerfile
            context: .
        ports:
            - "7002:7002"
            - "7003:7003"
        hostname: spqr_coordinator
    world1:
        image:
            spqr_shardbase
#        build:
#            dockerfile: ./docker/world/Dockerfile
#            context: .
        hostname: spqr_world_0_1
        ports:
            - "7434:6432"
    qdb01:
        image: 'bitnami/etcd:latest'
        hostname: spqr_qdb_0_1
        environment:
            ALLOW_NONE_AUTHENTICATION: "yes"
            ETCD_LOG_LEVEL: "debug"
        ports:
            - "2379:2379"
    router:
        build:
            dockerfile: ./docker/router/Dockerfile
            context: .
        ports:
            - "8432:6432"
        hostname: spqr_router_1_1
    balancer:
        build:
            dockerfile: ./docker/balancer/Dockerfile
            context: .
        hostname: spqr_balancer
    db0:
        image:
            spqr_shardbase
        ports:
            - "7435:6432"
        hostname: spqr_db_0_1
    client:
        build:
            dockerfile: ./docker/tests/Dockerfile
            context: .
        hostname: spqr_client

networks:
    spqr:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.233.0/24
